name: Setup Python & Cargo
description: Setup Python & Cargo

inputs:
  python-version:
    description: Python version
    required: false
    default: "3.10"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      name: Setup Python
      with:
        python-version: ${{ inputs.python-version }}
        architecture: "x64"

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable