name: Release and Publish

on:
  push:
    tags:
      - v*

jobs:
  build_and_upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-22.04]
        arch: ['x64']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Libraries
        uses: ./.github/actions/build-libraries
        with:
          os: ${{ matrix.os }}


  release_and_publish:
    # 发布到 GitHub Release
    runs-on: ubuntu-latest
    needs: build_and_upload

    steps:
      - name: Checkout Code (all commits)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Download Libraries
        uses: ./.github/actions/download-libraries
        with:
          artifacts: ${{ needs.build_and_upload.outputs.artifact_name }}
          output_target: libraries


      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Create release
        run: npx changelogithub-chinese
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}


      - name: Upload DLL to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./libraries/*
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}